channels:
- conda-forge
dependencies:
- cmake
- doxygen >=1.9.5
- h5py
- mathjax
- ninja
- numpy
- prrng >=1.5.1
- pybind11
- python
- scikit-build
- scipy
- setuptools_scm
- xtensor
- xtensor-python
